services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - services
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - services
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - services
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

networks:
  services:
    driver: bridge
