apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-frontend
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-frontend
  template:
    metadata:
      labels:
        app: auth-frontend
    spec:
      containers:
        - name: auth-frontend
          image: samarthasthan/auth-frontend:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost:8001/v1"
            - name: PORT
              value: "3001"
            - name: HOSTNAME
              value: "0.0.0.0"
          ports:
            - containerPort: 3001
