apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  namespace: services
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: auth.frubay.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-frontend
                port:
                  number: 3001
    - host: frubay.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-frontend
                port:
                  number: 3000
    - host: api.frubay.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-gateway
                port:
                  number: 8001
