apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: services
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.images.kafka }}"
          envFrom:
            - configMapRef:
                name: services-config
          ports:
            - name: client
              containerPort: 29092
            - name: external
              containerPort: 9092
            - name: controller
              containerPort: 9093
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "200m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "400m"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.kafkaSize }}
        {{- if .Values.persistence.kafkaLocalPath }}
        storageClassName: ""
        selector:
          matchLabels:
            statefulset: kafka 
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: services
spec:
  selector:
    app: kafka
  ports:
    - name: client
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
  clusterIP: None