apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: services
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.images.postgres }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: services-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: services-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: services-secret
                  key: DB_NAME
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.postgresSize }}
        {{- if .Values.persistence.postgresLocalPath }}
        storageClassName: ""
        selector:
          matchLabels:
            statefulset: postgres 
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: services
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None