apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: temporal
  namespace: services
spec:
  serviceName: temporal
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: "{{ .Values.images.temporal }}"
          env:
            - name: DB
              value: "postgres12"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: services-secret
                  key: DB_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: services-secret
                  key: DB_PASSWORD
            - name: POSTGRES_SEEDS
              value: "postgres-0.postgres.services.svc.cluster.local"
            - name: ENABLE_ES
              value: "true"
            - name: ES_SEEDS
              value: "elasticsearch"
            - name: ES_VERSION
              value: "v7"
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: "/etc/temporal/config/dynamicconfig/development-sql.yaml"
            # Single-node configuration
            - name: TEMPORAL_BROADCAST_ADDRESS
              value: "0.0.0.0"
            - name: BIND_ON_IP
              value: "0.0.0.0"
            # Services configuration for single node
            - name: SERVICES
              value: "history,matching,frontend,worker"
            # Skip setup flags
            - name: SKIP_SCHEMA_SETUP
              value: "false"
            - name: SKIP_DEFAULT_NAMESPACE_CREATION
              value: "false"
          ports:
            - containerPort: {{ .Values.env.TEMPORAL_PORT }}
              name: grpc
            - containerPort: 8233
              name: web
          volumeMounts:
            - name: temporal-config
              mountPath: /etc/temporal/config/dynamicconfig
          # More generous health checks for startup
          livenessProbe:
            tcpSocket:
              port: {{ .Values.env.TEMPORAL_PORT }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.env.TEMPORAL_PORT }}
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: temporal-config
          hostPath:
            path: /Users/samarthasthan/personal/services-commons/build/dynamicconfig
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: services
spec:
  selector:
    app: temporal
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
      protocol: TCP
    - name: web
      port: 8233
      targetPort: 8233
      protocol: TCP
  type: ClusterIP