apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-admin-tools
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-admin-tools
  template:
    metadata:
      labels:
        app: temporal-admin-tools
    spec:
      containers:
        - name: temporal-admin-tools
          image: "{{ .Values.images.temporalAdminTools }}"
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal:{{ .Values.env.TEMPORAL_PORT }}"
            - name: TEMPORAL_CLI_ADDRESS
              value: "temporal:{{ .Values.env.TEMPORAL_PORT }}"
          stdin: true
          tty: true
