apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-grpc
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-grpc
  template:
    metadata:
      labels:
        app: file-grpc
    spec:
      containers:
        - name: file-grpc
          image: samarthasthan/file-service:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: POSTGRES_HOST
              value: "postgres-0.postgres.services.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: MONGO_HOST
              value: "mongo-0.mongo.services.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: "{{ .Values.env.MONGO_USER }}"
            - name: MONGO_PASSWORD
              value: "{{ .Values.env.MONGO_PASSWORD }}"
            - name: MONGO_DATABASE
              value: "{{ .Values.env.MONGO_DATABASE }}"
            - name: FILE_SERVICE_HOST
              value: "0.0.0.0"
            - name: FILE_SERVICE_PORT
              value: "50054"
            - name: USER_SERVICE_HOST
              value: "user-grpc.services.svc.cluster.local"
            - name: USER_SERVICE_PORT
              value: "50051"
            - name: AUTH_SERVICE_HOST
              value: "auth-grpc.services.svc.cluster.local"
            - name: AUTH_SERVICE_PORT
              value: "50052"
            - name: KAFKA_EXTERNAL_PORT
              value: "29092"
            - name: KAFKA_HOST
              value: "kafka-0.kafka.services.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: "redis-0.redis.services.svc.cluster.local"
            - name: REDIS_PASSWORD
              value: "{{ .Values.env.REDIS_PASSWORD }}"
            - name: S3_ENDPOINT
              value: "https://eu2.contabostorage.com"
            - name: S3_ACCESS_KEY
              value: "{{ .Values.env.S3_ACCESS_KEY }}"
            - name: S3_SECRET_KEY
              value: "{{ .Values.env.S3_SECRET_KEY }}"
            - name: S3_BUCKET
              value: "frubay-cloud"
            - name: S3_REGION
              value: "eu2"
            - name: S3_USE_SSL
              value: "true"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 50054

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: file-grpc-hpa
  namespace: services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-grpc
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70